/**
 * Generate the CROSS-REPO fixture for GET /api/fp/progress.
 *
 *   npx tsx scripts/gen-fp-progress-fixture.ts \
 *     > ../first-profit/src/screens/staff/__tests__/fixtures/progress-response.json
 *
 * ── Why this script exists ──
 * The wire shape of this endpoint is DECLARED TWICE: `ProgressChild` here and
 * `WireChild` in first-profit's `src/screens/staff/flowBoard.ts`. Both
 * declarations were written from the same reading of the same header, and
 * neither repo's suite has ever seen a byte the other actually produced — so a
 * field rename on this side is a silent `undefined` at runtime in the staff
 * board with every test in both suites green. That is the ROOT CAUSE of a whole
 * class of seam bugs, not one instance of it.
 *
 * So: this script runs the REAL `shapeProgress` over a representative store and
 * prints the exact success body the route emits (`{"ok":true,"children":[…]}`).
 * The output is committed in first-profit and read by
 * `src/screens/staff/__tests__/wireFixture.test.ts`, which asserts that
 * `narrowProgress` accepts it unchanged (no rejected children, ideas or
 * businesses) and that `normalizeCohort` derives the units it should.
 *
 * ── Keeping it honest ──
 * It calls `shapeProgress` directly rather than booting the route: the route
 * adds only auth, paging and serialization, none of which shape a field name,
 * and a fixture that needed a database would be regenerated by nobody. Every
 * field of the contract must be EXERCISED by at least one child below — a field
 * that is always null or always absent is a field the fixture cannot pin.
 *
 * Deterministic by construction: fixed ids, fixed stamps, and a fixed `now`, so
 * regenerating with no source change produces a byte-identical file and the diff
 * is always the contract change and nothing else.
 */
import {
  shapeProgress,
  type ProgressChildRowLike,
  type ProgressProfileRowLike,
  type ProgressSaveRowLike,
} from "@/app/api/fp/progress/progress-rules";

/** Fixed instant. Everything below is stated as an offset from it, so the file
 *  never changes because a day passed. */
const NOW = new Date("2026-08-05T12:00:00.000Z");
const NOW_MS = NOW.getTime();
const DAY = 86_400_000;

/** The ids a real client asks for when the board is on criterion 1.2: that
 *  criterion's tasks, the ONE entry predecessor from 1.1, and the legacy
 *  spellings of both (see first-profit's `requestedTaskIds`). */
const REQUESTED = ["1.1.5", "1.1#4", "1.2.1", "1.2.2", "1.2.3", "1.2#0", "1.2#1", "1.2#2"];

/** Phase 4 ids, so the business half of the contract is exercised too. Both
 *  criteria ride in one request here — the shape is what is being pinned, not
 *  the client's windowing. */
const REQUESTED_GROW = ["4.1.1", "4.1.2"];

const docOf = (body: Record<string, unknown>): Record<string, unknown> => ({
  docVersion: 1,
  ...body,
});

const children: ProgressChildRowLike[] = [
  { id: "c-1", fp_username: "ada.fp" },
  { id: "c-2", fp_username: "bo.fp" },
  { id: "c-3", fp_username: "cy.fp" },
  { id: "c-4", fp_username: "di.fp" },
  // Roster row, no profile, no save: the "never signed in" child. Present with
  // empty arrays — an absent child is indistinguishable from a fresh one.
  { id: "c-5", fp_username: "eve.fp" },
  // A save row this build cannot read: `docUnreadable`, which is NOT the same
  // fact as "never started" and must not be foldable into it.
  { id: "c-6", fp_username: "fi.fp" },
];

const profiles: ProgressProfileRowLike[] = [
  { id: "p-1", child_id: "c-1" },
  { id: "p-2", child_id: "c-2" },
  { id: "p-3", child_id: "c-3" },
  { id: "p-4", child_id: "c-4" },
  { id: "p-6", child_id: "c-6" },
];

const saves: ProgressSaveRowLike[] = [
  {
    // ada: two ideas. The first is mid-criterion with real timestamped
    // completions (a usable cycle-time pair); the second is stable-id keyed and
    // carries completions the request did not ask about.
    profile_id: "p-1",
    doc: docOf({
      ideas: [
        {
          id: "idea-a1",
          fields: { productName: "Dog treats" },
          doneByTask: { "1.1.5": true, "1.2.1": true },
          doneAtByTask: { "1.1.5": NOW_MS - 5 * DAY, "1.2.1": NOW_MS - 3 * DAY },
        },
        {
          id: "idea-a2",
          // Out-of-request completions: `hasCompletionsOutsideRequest` true, and
          // `lastCompletionAt` computed BEFORE the filter.
          doneByTask: { "1.1.5": true, "1.2.1": true, "1.2.2": true, "3.1.1": true },
          doneAtByTask: {
            "1.1.5": NOW_MS - 40 * DAY,
            "1.2.1": NOW_MS - 39 * DAY,
            "1.2.2": NOW_MS - 38 * DAY,
            "3.1.1": NOW_MS - 2 * DAY,
          },
        },
      ],
    }),
  },
  {
    // bo: LEGACY maps only (the pre-stable-id spelling), plus an idea with NO
    // id at all — the client mints `legacy-idea-{index}` from the preserved
    // original index, so the index must survive the wire.
    profile_id: "p-2",
    doc: docOf({
      ideas: [
        {
          id: "idea-b1",
          done: { "1.1#4": true, "1.2#0": true },
          doneAt: { "1.1#4": NOW_MS - 9 * DAY, "1.2#0": NOW_MS - 6 * DAY },
        },
        // A malformed entry: a PLACEHOLDER at its original index, never a hole.
        "MALFORMED",
        {
          doneByTask: { "1.1.5": true },
          doneAtByTask: { "1.1.5": NOW_MS - 200 * DAY },
        },
      ],
    }),
  },
  {
    // cy: the BUSINESS half. One promoted business folded onto its idea, one
    // ARCHIVED business (completions fold, recency does not), and one DANGLING
    // business whose ideaId names nothing — its own flow unit.
    profile_id: "p-3",
    doc: docOf({
      ideas: [
        {
          id: "idea-c1",
          doneByTask: { "1.1.5": true, "1.2.1": true, "1.2.2": true, "1.2.3": true },
          doneAtByTask: {
            "1.1.5": NOW_MS - 90 * DAY,
            "1.2.1": NOW_MS - 88 * DAY,
            "1.2.2": NOW_MS - 87 * DAY,
            "1.2.3": NOW_MS - 80 * DAY,
          },
        },
      ],
      businesses: [
        {
          id: "biz-c1",
          ideaId: "idea-c1",
          archived: false,
          doneByTask: { "4.1.1": true },
          doneAtByTask: { "4.1.1": NOW_MS - 1 * DAY },
        },
        {
          id: "biz-c2",
          ideaId: "idea-c1",
          archived: true,
          doneByTask: { "4.1.2": true },
          doneAtByTask: { "4.1.2": NOW_MS - 2 * DAY },
        },
        {
          id: "biz-c3",
          ideaId: "no-such-idea",
          doneByTask: { "4.1.1": true },
          doneAtByTask: { "4.1.1": NOW_MS - 120 * DAY },
        },
      ],
    }),
  },
  {
    // di: the ANOMALIES. A FUTURE stamp (clamped, `recencyClamped` true), a bare
    // `doneAtByTask` key with no `doneByTask` (a stamp that is not a completion,
    // so `lastCorroboratedCompletionAt` LAGS `lastCompletionAt`), and a
    // malformed business entry, which flags `truncated`.
    profile_id: "p-4",
    doc: docOf({
      ideas: [
        {
          id: "idea-d1",
          // A real, timestamped pair — so this unit WOULD contribute a cycle
          // time if the clamp did not disqualify its clock.
          doneByTask: { "1.1.5": true, "1.2.1": true },
          doneAtByTask: {
            "1.1.5": NOW_MS - 300 * DAY,
            "1.2.1": NOW_MS - 298 * DAY,
            // Bare AND future: no `doneByTask` beside it, so it is not a
            // completion, and it is past the tolerance, so it is clamped.
            "1.2.2": NOW_MS + 400 * DAY,
          },
        },
      ],
      businesses: [{ ideaId: "idea-d1" }],
    }),
  },
  // A docVersion this build does not understand. The child's OWN client refuses
  // it too, so they are staring at an empty factory floor — never "not started".
  { profile_id: "p-6", doc: { docVersion: 99, ideas: [{ id: "idea-f1" }] } },
];

const body = {
  ok: true,
  children: shapeProgress(
    children,
    profiles,
    saves,
    [...REQUESTED, ...REQUESTED_GROW],
    NOW
  ),
};

process.stdout.write(`${JSON.stringify(body, null, 2)}\n`);
